steps:
    - commands:
          - "swift package clean"
          - "swift build"
          - "swift test"
          - "xcodebuild -scheme 'MetalSupport' -allowProvisioningUpdates -destination 'generic/platform=macOS'"
          - "xcodebuild -scheme 'MetalSupport' -allowProvisioningUpdates -destination 'generic/platform=iOS'"
          - "swiftlint lint --quiet"
