name: Swift
on:
  push:
  pull_request:

env:
  XCODE_VERSION: "26.2"

jobs:
  build:
    runs-on: macos-26
    steps:
      - uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1.7.0
        with:
          xcode-version: ${{ env.XCODE_VERSION }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: swift build -v
      - run: swift test -v

  build-ios:
    runs-on: macos-26
    steps:
      - uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1.7.0
        with:
          xcode-version: ${{ env.XCODE_VERSION }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Trust plugins
        run: defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidation -bool YES
      - name: Create iOS destination
        run: |
          SDK_PATH=$(xcrun --sdk iphoneos --show-sdk-path)
          TOOLCHAIN_BIN=$(dirname $(xcrun --find swiftc))
          IOS_VERSION=$(xcrun --sdk iphoneos --show-sdk-version)
          cat > .ios-destination.json << EOF
          {
              "version": 1,
              "sdk": "$SDK_PATH",
              "toolchain-bin-dir": "$TOOLCHAIN_BIN",
              "target": "arm64-apple-ios$IOS_VERSION",
              "extra-cc-flags": [],
              "extra-swiftc-flags": [],
              "extra-cpp-flags": []
          }
          EOF
      - name: Build (iOS)
        run: swift build -v --destination .ios-destination.json

  swiftlint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: brew install swiftlint
      - run: swiftlint --strict
